theme: jekyll-theme-hacker
title: Synalytica FZE
description: Quantitative finance | blockchain | AI | wellness
github.repository_url: https://github.com/Synalytica
google_analytics: [G-4T9WTY7SLD]
paginate: 5
paginate_path: /blog/page:num/